IF DB_ID(N'QuanLyThuVien') IS NOT NULL


CREATE DATABASE [QuanLyThuVien];
GO

USE [QuanLyThuVien];
GO

CREATE TABLE TheLoai (
	MaTheLoai NVARCHAR(20) NOT NULL PRIMARY KEY,
	TenTheLoai NVARCHAR(100) NOT NULL UNIQUE,
	MoTa NVARCHAR(255) NULL
);
GO

CREATE TABLE Sach (
	MaSach NVARCHAR(20) NOT NULL PRIMARY KEY,
	TieuDe NVARCHAR(255) NOT NULL,
	TacGia NVARCHAR(255) NOT NULL,
	MaTheLoai NVARCHAR(20),
	NamXuatBan INT,
	NgonNgu NVARCHAR(50) NULL,
	TomTat NVARCHAR(MAX) NULL,
	FOREIGN KEY (MaTheLoai) REFERENCES TheLoai(MaTheLoai)
);

CREATE TABLE KeSach (
	MaKe NVARCHAR(20) NOT NULL PRIMARY KEY,
	ViTri NVARCHAR(100) NULL
);

CREATE TABLE BanDoc (
	MaBanDoc NVARCHAR(20) NOT NULL PRIMARY KEY,
	SoThe NVARCHAR(10) NOT NULL UNIQUE,
	HoTen NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NULL,
	DienThoai NVARCHAR(10) NULL,
	HanThe DATE NOT NULL,
	TrangThaiThe NVARCHAR(20) NOT NULL CHECK (TrangThaiThe IN(N'Hoạt động', N'Bị khoá', N'Hết hạn')),
	DuNo DECIMAL(12,2) NOT NULL DEFAULT(0) CHECK (DuNo >= 0)
);

CREATE TABLE BanSao (
	MaBanSao NVARCHAR(20) NOT NULL PRIMARY KEY,
	MaVach NVARCHAR(64) NOT NULL,
	MaSach NVARCHAR(20) NOT NULL,
	MaKe NVARCHAR(20) NOT NULL,
	TrangThai NVARCHAR(20) NOT NULL CHECK (TrangThai IN(N'Có sẵn', N'Đang mượn', N'Hư hỏng')),

	FOREIGN KEY (MaSach) REFERENCES Sach(MaSach),
	FOREIGN KEY (MaKe) REFERENCES KeSach(MaKe)
);

CREATE TABLE PhieuMuon (
	MaPhieuMuon NVARCHAR(20) NOT NULL PRIMARY KEY,
	MaBanSao NVARCHAR(20) NOT NULL,
	MaBanDoc NVARCHAR(20) NOT NULL,
	NgayMuon DATE NOT NULL,
	HanTra DATE NOT NULL,
	NgayTraThucTe DATE NULL,
	SoLanGiaHan INT NOT NULL DEFAULT(0) CHECK(SoLanGiaHan >= 0),
	TrangThai NVARCHAR(10) CHECK(TrangThai IN(N'Đang mở', N'Đã đóng')),

	FOREIGN KEY (MaBanSao) REFERENCES BanSao(MaBanSao),
	FOREIGN KEY (MaBanDoc) REFERENCES BanDoc(MaBanDoc)
);

CREATE TABLE DatCho (
	MaDatCho NVARCHAR(20) NOT NULL PRIMARY KEY,
	MaSach NVARCHAR(20) NOT NULL,
	MaBanDoc NVARCHAR(20) NOT NULL,
	NgayTao DATETIME NOT NULL DEFAULT (SYSUTCDATETIME()),
	TrangThai NVARCHAR(20) NOT NULL CHECK (TrangThai IN (N'Chờ hàng', N'Đang giữ', N'Đã hủy', N'Hết hạn')),
	GiuDen DATETIME NULL,
	FOREIGN KEY (MaSach) REFERENCES Sach(MaSach),
	FOREIGN KEY (MaBanDoc) REFERENCES BanDoc(MaBanDoc)
);
GO


CREATE TABLE ThanhToan (
	MaThanhToan NVARCHAR(20) NOT NULL PRIMARY KEY,
	MaBanDoc NVARCHAR(20) NOT NULL,
	NgayThanhToan DATETIME NOT NULL DEFAULT (SYSUTCDATETIME()),
	SoTien DECIMAL(12,2) NOT NULL CHECK (SoTien >= 0),
	HinhThuc NVARCHAR(20) NOT NULL CHECK (HinhThuc IN (N'Tiền mặt', N'Thẻ', N'Chuyển khoản', N'Ví điện tử')),
	GhiChu NVARCHAR(255) NULL,
	FOREIGN KEY (MaBanDoc) REFERENCES BanDoc(MaBanDoc)
);
GO


CREATE TABLE Phat (
	MaPhat NVARCHAR(20) NOT NULL PRIMARY KEY,
	MaPhieuMuon NVARCHAR(20) NOT NULL,
	SoTien DECIMAL(12,2) NOT NULL CHECK (SoTien >= 0),
	LyDo NVARCHAR(20) NOT NULL CHECK (LyDo IN (N'Trễ hạn', N'Hư hỏng', N'Mất', N'Khác')),
	NgayTinh DATETIME NOT NULL DEFAULT (SYSUTCDATETIME()),
	TrangThai NVARCHAR(20) NOT NULL CHECK (TrangThai IN (N'Chưa trả', N'Đã trả', N'Miễn')),
	MaThanhToan NVARCHAR(20) NULL,
	FOREIGN KEY (MaPhieuMuon) REFERENCES PhieuMuon(MaPhieuMuon),
	FOREIGN KEY (MaThanhToan) REFERENCES ThanhToan(MaThanhToan)
);
GO


CREATE TABLE TaiKhoan (
	MaTaiKhoan NVARCHAR(20) NOT NULL PRIMARY KEY,
	TenDangNhap NVARCHAR(100) NOT NULL UNIQUE,
	MatKhau NVARCHAR(255) NOT NULL,
	VaiTro NVARCHAR(20) NOT NULL CHECK (VaiTro IN (N'Quản trị', N'Thủ thư', N'Bạn đọc')),
	MaBanDoc NVARCHAR(20) NULL,
	FOREIGN KEY (MaBanDoc) REFERENCES BanDoc(MaBanDoc)
);
GO

